name: Publish to PyPi.

on:
  release:
    types: [ published ]

jobs:
  build-n-publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install wheel
        run: python3 -m pip install wheel
      - name: Build a binary wheel and a source tarball
        run: python3 setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}